apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      restartPolicy: Always
      containers:
        - name: backend-user
          imagePullPolicy: Always
          image: togunfile/udagram-api-user:v1
          # ports:
          #   - containerPort: 8080
          resources:
            limits:
              cpu: 512m
            requests:
              cpu: 256m
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: URL
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: AWS_REGION
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: AWS_BUCKET
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: JWT_SECRET
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-user