apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      restartPolicy: Always
      containers:
        - name: backend-user
          imagePullPolicy: Always
          image: togunfile/udagram-api-user:v2
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "512m"
              memory: "1Gi"
            requests:
              cpu: 1
              memory: "500Mi"
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: URL
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: AWS_REGION
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: AWS_BUCKET
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-user